version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - "8000:8000"
    networks:
      - sma-network
    volumes:
      - .:/app
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    ports:
      - "8501:8501"
    networks:
      - sma-network
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - sma-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - sma-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP
      - "9464:9464" # Prometheus metrics exporter
    networks:
      - sma-network

networks:
  sma-network:
    driver: bridge
