FROM python:3.10

WORKDIR /app

COPY requirements_fastapi.txt .

RUN apt-get update && apt-get install -y build-essential cmake gcc g++ python3-dev libopenblas-dev git curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_fastapi.txt

COPY . .

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
