FROM python:3.10

WORKDIR /app

COPY requirements_streamlit.txt .

RUN apt-get update && apt-get install -y build-essential cmake \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY . .

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
